[package]
name = "file_hash_checker_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
file_hash_checker = {path = "../file_hash_checker"}